import Head from 'next/head'
import useSWR from 'swr'
import ItemCarousel from "../components/ItemCarousel";
import {$products} from "../api";
import ProductCard from "../components/Card/ProductCard";
import ProductCardSkeleton from "../components/Card/ProductCardSkeleton";

async function fetcher() {
    const [items1, items2, items3] = await Promise.all([
        fetch(`${$products}/1`).then(value => value.json()),
        fetch(`${$products}/2`).then(value => value.json()),
        fetch(`${$products}/3`).then(value => value.json()),
    ]);
    return {items1, items2, items3};
}

const Home = (props) => {
    const {data, error} = useSWR('/', fetcher, {initialData: props, revalidateOnMount: true});
    let sliderItems1, sliderItems2, sliderItems3;
    if (error) return <div>Failed to load</div>
    const {items1, items2, items3} = data ||
    {items1: Array.from(Array(5).keys()), items2: Array.from(Array(5).keys()), items3: Array.from(Array(5).keys())};

    sliderItems1 = items1?.map(item => data ? <ProductCard key={item.key} item={item}/> : <ProductCardSkeleton/>)
    sliderItems2 = items2?.map(item => data ? <ProductCard key={item.key} item={item}/> : <ProductCardSkeleton/>)
    sliderItems3 = items3?.map(item => data ? <ProductCard key={item.key} item={item}/> : <ProductCardSkeleton/>)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <h2>اسلایدر یک</h2>
          <ItemCarousel items={sliderItems1}/>
          <hr/>
          <h2>اسلایدر دو</h2>
          <ItemCarousel items={sliderItems2}/>
          <hr/>
          <h2>اسلایدر سه</h2>
          <ItemCarousel items={sliderItems3}/>
      </main>
    </>
  )
}

export async function getStaticProps(context) {
    const data = await fetcher();
    return {props: data}
}

export default Home;
